version: '3'

services:
  developemnt:
    image: environment-php
    hostname: environment-php
    container_name: environment-php
    labels:
      description: environment-php
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - './:/app'
    env_file: 
      - ./.env.dev
    environment:
      PHP_ENV: "development"
      PHPPORT: 8000
      DB_HOST: 'mysql-db'
      DB_PORT: 3306
      DB_USERNAME: 'root'
      DB_DATABASE: 'laravel'
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - mysql-db

  mysql-db:
    image:  mysql:5.7
    hostname: environment-mysql
    container_name: environment-mysql
    labels:
      description: environment-mysql
    working_dir: /var/lib/mysql
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "root"
      # MYSQL_ROOT_PASSWORD: "Alterar123"
      # MYSQL_PASSWORD: "Alterar123"
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306 # host:container     