# ## enviroment laravel

# # maquina de instalação das dependencias
FROM docker.io/bitnami/laravel:9 AS environment-php-dependences

ENV APP_HOME /app
ENV TZ=America/Sao_Paulo

RUN apt -y update
RUN apt -y install tzdata

# ## NEW TIMEZONE
RUN echo $TZ > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

COPY ./ ./

# RUN composer install

# ## diretorio de trabalho
WORKDIR "$APP_HOME"

# ## maquina de desenvolvimento
FROM environment-php-dependences AS environment-php

## Labels
LABEL description="environment-php"

ENV APP_HOME /app

ENV PHPPORT=8000

# ## diretorio de trabalho
WORKDIR "$APP_HOME"

# ## copia a aplicacao para dentro da maquina
COPY ./ ./

## portas de acesso
EXPOSE "$PHPPORT"

# ## cria volume para diretorio padrao
VOLUME "$APP_HOME"

# ## Executa a aplicacao
CMD ["php", "artisan", "serve"]